trigger:
- feature/deploy-to-AKS

resources:
- repo: self

variables:
- template: vars.yml

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    
    - task: Docker@2
        displayName: Build an image
        inputs:
          containerRegistry: '${{ variables.containerRegistry }}'
          repository: '${{ variables.repository }}'
          command: 'buildAndPush'
          Dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
          tags: |
          '${{ variables.tag }}'
    
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/kubernetes'
        artifact: 'manifests'
        publishLocation: 'pipeline'
          
